learner_user: learning
learner_user_home: /home/{{learner_user}}
dial_service_path: "{{learner_user_home}}/platform/service"
dial_home: "{{learner_user_home}}/platform/dial/sunbird-dial-service"
dial_root: "{{learner_user_home}}/platform/dial"
platform_api_url: "http://{{ groups['learning1'][0] }}:8080/learning-service"
instance: "{{env}}"
instance_name: ekstep
service_path: /home/{{learner_user}}/platform/service
script_name: "sunbird-dial-service"
script_dir: "{{ service_path }}"
grep_key: play.core.server.ProdServerStart
process: "/usr/bin/java"
dial_root: /home/{{learner_user}}/platform/dial
service_args: "-Dconfig.file={{ dial_root }}/dial-service.conf"
dial_home: /home/{{learner_user}}/platform/dial/sunbird-dial-service
process_home: ""
app_home: "{{ dial_home }}"
process_args: -- -cp '{{ app_home }}/lib/*' {{ service_args }} play.core.server.ProdServerStart {{ app_home }}